highlighter: pygments

navigation:
- text: home
  url: /index.html
- text: attending
  url: /attending.html
- text: recorded
  url: /recorded.html
- text: about
  url: /about.html
social:
- text: YouTube
  url: https://www.youtube.com/@PhyloseminarOrg/streams
  icon: "fa-brands fa-youtube"
- text: Bluesky
  url: https://bsky.app/profile/phyloseminar.bsky.social
  icon: "fa-brands fa-bluesky"
- text: Twitter
  url: http://twitter.com/phyloseminar
  icon: "fa-brands fa-twitter"
- text: Google Groups
  url: https://groups.google.com/forum/?fromgroups#!forum/phyloseminar
  icon: "fa-solid fa-users"
- text: RSS
  url: http://phyloseminar.org/index.rss
  icon: "fa-solid fa-rss"
